### ISSUE TITLE
Software Must Access NWS when Available

### ISSUE THREAD

**Issue by wreuvekamp** [wreuvekamp/IoT-Monitoring-Backlog#1]
-Figure what API we need to hit to get our information.
-Use API calls with Python

Effort Points:
6

Priority:
High 1

**Comment by WimReuvekampSDSU** [comment]
The effort points and rationale of the 1-8 point range.

- '1' effort is minimal, and not going to take long
- '8' effort is max, in that it will likely take the whole sprint

The thought process behind our priority rankings:

- '1' is a high priority; necessary to continue the project
- '5' is a medium priority; not immediately necessary but useful
- '10' is low priority; can be suspended or optional as the project progresses
